spring:
  application:
    name: todo

  datasource:
    url: jdbc:mysql://localhost:3306/to-do?useSSL=false
    username: root
    password: Root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8083
